# Columns Transformation

In [1]:
import pandas as pd

### Calculated Column

In [2]:
data = pd.read_excel('columns_transformation.xlsx')
data['Total_Sale'] = (data['Sales'] * data['Quantity'])
data['Discount'] = data['Total_Sale'] / 100 * 2
data

,Order_Number,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Sale,Discount
0,139374,Adhir Samal,2020-01-11,Delivered,512 GB M.2,SSD,Samsung,6500,8450,1,8450,169.0
1,139375,Dannana Jhammi,2020-01-11,Delivered,RYZEN 3rd gen. 3500,CPU,Intel,8500,11050,3,33150,663.0
2,139376,Vipin Kumar,2020-01-11,Delivered,2GB Graphic Card,Graphic Card,Nvidia,7000,9100,2,18200,364.0
3,139377,Ranjeet Kumar,2020-01-11,Delivered,16 GB DDR4 RAM,RAM,Hynix,6550,8515,3,25545,510.9
4,139378,Sajal Singhal,2020-01-11,Order,Standard ATX motherboard,MotherBoard,Gigabyte,7650,9945,4,39780,795.6
5,139379,Akhilesh Kumar,2020-01-11,Order,Compact with 1 Fan,Cabinet,Asus,1150,1495,2,2990,59.8
6,139380,Suvankar Chakraborty,2020-01-11,Order,USB Backlight Keyboard,Keyboard,Dell,850,1105,3,3315,66.3
7,139381,Suvankar Adhikary,2020-01-12,Order,Ergonomic Mouse,Mouse,Samsung,650,845,2,1690,33.8
8,139382,Rahul Kumar Prajapati,2020-01-13,Order,"15"" LCD Dsipaly",Monitor,Dell,7500,9750,1,9750,195.0

In [5]:
data = pd.read_excel('columns_transformation.xlsx')
data

,Order_Number,Customer_Name,Order_Date,Month,Status,Product,Category,Brand,Cost,Sales,Quantity
0,139374,Adhir Samal,2020-01-11,January,Delivered,512 GB M.2,SSD,Samsung,6500,8450,1
1,139375,Dannana Jhammi,2020-02-11,February,Delivered,RYZEN 3rd gen. 3500,CPU,Intel,8500,11050,3
2,139376,Vipin Kumar,2020-03-11,March,Delivered,2GB Graphic Card,Graphic Card,Nvidia,7000,9100,2
3,139377,Ranjeet Kumar,2020-04-11,April,Delivered,16 GB DDR4 RAM,RAM,Hynix,6550,8515,3
4,139378,Sajal Singhal,2020-05-11,May,Order,Standard ATX motherboard,MotherBoard,Gigabyte,7650,9945,4
5,139379,Akhilesh Kumar,2020-06-11,June,Order,Compact with 1 Fan,Cabinet,Asus,1150,1495,2
6,139380,Suvankar Chakraborty,2020-07-11,July,Order,USB Backlight Keyboard,Keyboard,Dell,850,1105,3
7,139381,Suvankar Adhikary,2020-08-12,August,Order,Ergonomic Mouse,Mouse,Samsung,650,845,2
8,139382,Rahul Kumar Prajapati,2020-09-13,September,Order,"15"" LCD Dsipaly",Monitor,Dell,7500,9750,1

### Extracting a column data using map function.

In [8]:
def extract(value):
    return value[0:3]


data["Short_Month"] = data["Month"].map(extract)
data

,Order_Number,Customer_Name,Order_Date,Month,Status,Product,Category,Brand,Cost,Sales,Quantity,Short_Month
0,139374,Adhir Samal,2020-01-11,January,Delivered,512 GB M.2,SSD,Samsung,6500,8450,1,Jan
1,139375,Dannana Jhammi,2020-02-11,February,Delivered,RYZEN 3rd gen. 3500,CPU,Intel,8500,11050,3,Feb
2,139376,Vipin Kumar,2020-03-11,March,Delivered,2GB Graphic Card,Graphic Card,Nvidia,7000,9100,2,Mar
3,139377,Ranjeet Kumar,2020-04-11,April,Delivered,16 GB DDR4 RAM,RAM,Hynix,6550,8515,3,Apr
4,139378,Sajal Singhal,2020-05-11,May,Order,Standard ATX motherboard,MotherBoard,Gigabyte,7650,9945,4,May
5,139379,Akhilesh Kumar,2020-06-11,June,Order,Compact with 1 Fan,Cabinet,Asus,1150,1495,2,Jun
6,139380,Suvankar Chakraborty,2020-07-11,July,Order,USB Backlight Keyboard,Keyboard,Dell,850,1105,3,Jul
7,139381,Suvankar Adhikary,2020-08-12,August,Order,Ergonomic Mouse,Mouse,Samsung,650,845,2,Aug
8,139382,Rahul Kumar Prajapati,2020-09-13,September,Order,"15"" LCD Dsipaly",Monitor,Dell,7500,9750,1,Sep